name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        os: [ windows, darwin ]
        exclude:
          - arch: arm64
            os: windows
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
        
      - name: Generate build file
        run: go build -o "dist/rep-${{ matrix.os }}{{ matrix.arch }}" main.go
        
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: go-build-files
          path: dist/*
